# Generated by Django 4.1.1 on 2022-10-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base',
            new_name='Alumno',
        ),
    ]
